### PR TITLE
feat: added grids component

### PR DESCRIPTION
**Pull request by GuptaEesh**
Added 2 grids:

>2-Grid System
3-Grid System

grid

### CODE REVIEW

**Review by saadahmadhere — APPROVED** [review]
Code looks clean to me.

**Review by Hamdrive — APPROVED** [review]
Good work done, maybe you can be more specific with class names
since you are creating for columns, you can try something like `grid-cols-2` etc

Optional, else everything looks good and can be merged

**Comment by dubeyaditya29** [comment]
The code looks clean and best practices followed good to merge.

**Review by dubeyaditya29 — APPROVED** [review]

**Comment by GuptaEesh** [comment]
Actually i didn't specify rows as they are automatically generated if not specified. So, any name would work. Merging it.

**Pull request merged**
