### PR TITLE
feat: added snackbar component

### PR DESCRIPTION
**Pull request by GuptaEesh**
4 types of snack bar are added:

>Baseline Simple
Baseline Stacked
Leading Simple
Leading Stacked

simple
stacked

### CODE REVIEW

**Review by MaruthiPothuganti — COMMENTED** [review]
Everything looks good. Just a suggestion: Try having  uniform space around the content of snackbar

**Review by ZuberDunge — APPROVED** [review]
Clean and easily understandable code structure. UI Design looks great too. Good to merge from my side.

**Review by MaruthiPothuganti — COMMENTED** [review]
Everything looks good. Just a suggestion: Try having  uniform space around the content of snackbar

**Comment by GuptaEesh** [comment]
Got 2 reviews. I would say design is subjective.😅

**Pull request merged**
